This workflow is disabled. See android-ci.yml for the active CI workflow.
The original workflow tried to build release APKs which require keystore secrets.
For CI purposes, we build debug APKs which don't require signing.

     - name: Create and push new tag
       run: |
         git tag ${{ steps.version.outputs.new_tag }}
         git push origin ${{ steps.version.outputs.new_tag }}

     - name: Release APK to Target Repository
       uses: softprops/action-gh-release@v2
       with:
         files: ./artifact/*
         repository: BitBashOwn/appilot-APK
         tag_name: ${{ steps.version.outputs.new_tag }}
         token: ${{ secrets.TARGET_REPO_ACCESS_TOKEN }}
       env:
         GITHUB_TOKEN: ${{ secrets.TARGET_REPO_ACCESS_TOKEN }}

This entire workflow is disabled to prevent GitHub Actions permission issues.
The android-ci.yml workflow handles basic CI builds without requiring special permissions.

If you need release builds with automatic tagging in the future:
1. Set up repository secrets (KEYSTORE_BASE64, KEYSTORE_PASSWORD, etc.)  
2. Configure proper GitHub token permissions
3. Enable workflow by uncommenting and configuring the sections below

For now, use the simple android-ci.yml workflow for CI builds.
